config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  get 'contact', to: 'static_pages#contact'
  get 'beaux_et_services', to: 'static_pages#beaux_et_services'
  get 'coloc', to: 'static_pages#coloc'
  get 'studio', to: 'static_pages#studio'
  get 'appart', to: 'static_pages#appart'
  get 'ch1', to: 'static_pages#ch1'
  get 'ch2', to: 'static_pages#ch2'
  get 'ch3', to: 'static_pages#ch3'
  get 'ch4', to: 'static_pages#ch4'
  get 'ch5', to: 'static_pages#ch5'
  get 'ch6', to: 'static_pages#ch6'
  get 'ch7', to: 'static_pages#ch7'
  get 'parties_communes', to: 'static_pages#parties_communes'
  get 'st1', to: 'static_pages#st1'
  get 'st2', to: 'static_pages#st2'
  get 'st3', to: 'static_pages#st3'
  get 'st4', to: 'static_pages#st4'
  get 'st5', to: 'static_pages#st5'
  get 'commun_studios', to: 'static_pages#commun_studios'
  get 'ach1', to: 'static_pages#ach1'
  get 'ach2', to: 'static_pages#ach2'
  get 'ach3', to: 'static_pages#ach3'
  get 'commun_appart', to: 'static_pages#commun_appart'
  resources :houses do
    resources :rooms
  end

  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  root 'homes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/house.rb
class House < ApplicationRecord
  has_many :rooms
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :room
  # has_one_attached :image
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :house
  has_many :photos, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

  def not_found
    render status: 404
  end

  def unacceptable
    render status: 422
  end

  def internal_server_error
    render status: 500
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: %i[ show edit update destroy ]

  # GET /houses or /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1 or /houses/1.json
  def show
    @house = House.find(params[:id])
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses or /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to house_url(@house), notice: "House was successfully created." }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1 or /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to house_url(@house), notice: "House was successfully updated." }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1 or /houses/1.json
  def destroy
    @house.destroy

    respond_to do |format|
      format.html { redirect_to houses_url, notice: "House was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def house_params
      params.require(:house).permit(:room_id, :name)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]
  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
  end

  def beaux_et_services
  end

  def coloc
  end

  def studio
  end

  def ch1
  end

  def ch2
  end

  def ch3
  end

  def ch4
  end

  def ch5
  end

  def ch6
  end

  def ch7
  end

  def parties_communes
  end

  def st1
  end

  def st2
  end

  def st3
  end

  def st4
  end

  def st1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/homes/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(https://static.wixstatic.com/media/9f5c91_8621987c84f247f38a24e0805d0c0152~mv2.jpg/v1/crop/x_0,y_106,w_1600,h_484/fill/w_1089,h_330,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/redon-1718_-_e-_berthier_edited.jpg);">
<div class="container-title">
    <h1>ALCAMAYA</h1>
    <p>Location & Colocation Redon</p>
</div>
</div>

<div class="homepage-div-one">
    <div class="homepage-div-text">
      <h2>Découvrez nos chambres et studios</h2>
      <p>Dans des logements fraichement refaits à neuf, nous proposons une séléction de chambres et studios sur un grand terrain dans Redon. La thématique : un logement de qualité, un cadre de vie agréable et des locataires respectueux les uns des autres et désireux de faire des rencontres !</p>
    </div>


  <div class="button-space">
  <button class="button-home style-5" onclick="window.location.href='<%= houses_path %>'">Voir nos logements</button>
  <button class="button-home style-5" onclick="window.location.href='<%= contact_path %>'">Nous contacter</button>
  </div>
</div>

<div class="homepage-div">
    <div class="logo-display-green">
        <div class="logo-home">
          <i class="fa-solid fa-wifi fa-2xl" style="color: #56995e"></i>
          <p>Wi-Fi haut débit Fibre Optique</p>
        </div>
        <div class="logo-home">
          <i class="fa-solid fa-droplet fa-2xl" style="color: #56995e;"></i>
          <p>Toutes charges incluses Eau, Électricité, Internet, etc.</p>
        </div>
        <div class="logo-home">
          <i class="fa-solid fa-question fa-2xl" style="color: #56995e;"></i>
          <p>Assistance 24/7 En cas de problème</p>
        </div>
        <div class="logo-home">
          <i class="fa-solid fa-jug-detergent fa-2xl" style="color: #56995e;"></i>
          <p>Tout équipé* Lave-vaisselle, Machine à laver, Sèche-linge, etc.</p>
        </div>
        <div class="logo-home">
          <i class="fa-solid fa-broom fa-2xl" style="color: #56995e;"></i>
          <p>Ménage dans les parties communes - 2 fois/mois</p>
        </div>
        <div class="logo-home">
          <i class="fa-solid fa-tv fa-2xl" style="color: #56995e;"></i>
          <p>TV HD et abonnement Netflix*</p>
        </div>



        <div class="logo-home">
          <i class="fa-solid fa-house-user fa-2xl" style="color: #56995e;"></i>
          <p>Logement éligible APL</p>
        </div>
        <div class="logo-home">
          <i class="fa-solid fa-tree fa-2xl" style="color: #56995e;"></i>
          <p>Grand jardin aménagé Barbecue, table de jardin, transats</p>
        </div>
    </div>
  </div>
</div>

<div class="homepage-div-two">
    <div class="homepage-div-text-need">
      <div class="element-button"><h2 style="font-size: 20px;">Inclus dans la location</h2></div>
      <p>L'ensemble des services précédents sont inclus dans le loyer mensuel indiqué par chambre.</p>
      <p>Les services mentionnés avec un "*" ne sont pas inclus dans les studios.</p>
      <p>Les baux locatifs sont à titre individuel, chaque locataire aura son contrat, il n'y a pas de solidarité entre les contrats.</p>
    </div>
    <div class="homepage-div-text-need">
      <div class="element-button"><h2 style="font-size: 20px;">Ce que nous demandons</h2></div>
      <p>Nous demandons un dossier incluant les éléments suivants :</p>
      <ul>
        <li><strong>Document d'identité</strong></li>
        <li>Justificatif d'activité : <strong>Certificat de scolarité ou contrat de travail ou d'alternance ou de stage</strong></li>
        <li><strong>Justificatif d'activité d'un ou des garants</strong> : justificatif d'activité ou de propriété.</li>
        <li><strong>Une attestation d'assurance de responsabilité locative</strong></li>
      </ul>
      <p>Nous demandons à la signature une caution de l'équivalent d'un mois de loyer qui sera retournée à la fin du bail.</p>
      <p>Le contrat de bail prévoit un préavis de 1 mois.</p>
      <p>La durée minimale du bail est de 5 mois, les dossiers prévoyant une durée plus longue seront prioritaires.</p>
    </div>
</div>


<div class="homepage-div-green">
  <div class="contact-us">
    <h2>Contactez nous !</h2>
       <p style="text-align: center;"><i class="fa-solid fa-envelope" style="color: #000000;"> </i><strong>  Mail : alcamaya.contact@gmail.com</strong></p>
    <p style="text-align: center;"><i class="fa-solid fa-phone" style="color: #000000;"> </i><strong>  Tel : 06 87 19 94 04 (UNIQUEMENT SMS ou WHATSAPP)</strong></p>
  </div>
  <div class="map-placement">
  <a href="https://www.google.com/maps/place/Ti-Gar+Redon/@47.6519675,-2.0881564,15z/data=!4m6!3m5!1s0x480f9c0e60fb9fa3:0x69270737af0dea09!8m2!3d47.6519675!4d-2.0881564!16s%2Fm%2F0crgkcc?entry=ttu"><img class="map-redon" src="https://zupimages.net/up/23/29/2trm.png" alt=""></a>
  </div>
</div>

<style>
@media (max-width: 767px) {
    /* Ajoutez vos styles ici pour l'affichage sur les écrans plus petits */

    .homepage-div-one {
      display: block; /* Remplacer la disposition en grille par un affichage en bloc */
    }

    .homepage-div-text {
      margin: auto;
    }

    .button-space {
        text-align: center; /* Centrer les boutons */
        margin-top: 20px; /* Ajouter un espace entre les boutons */
        /* text-align: center; */
        margin-left: 0;
    }

    .logo-display-green {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 30px; /* Ajoutez un espacement entre les éléments si nécessaire */
    }

    .logo-home {
      margin-left: 20px;
      /* margin-bottom: 20px;  */
    }

    .homepage-div-two {
      display: block;
    }

    .homepage-div-text-need {
      margin: auto;
    }

    .homepage-div-green {
      display: block;
      align-items: center;
      justify-content: center;
      height: 100%%;
    }

    .contact-us {
      margin: auto;
    }

    .map-redon {
      width: 95%;
      height: 100%;
      /* margin: auto, */
      display: block;
      justify-content: center;
      align-items: center;
      /* height: 100%; */
      margin-top: 0;
      margin: auto;
      }
      /* Vous pouvez également ajuster la taille de la police, la marge, etc., pour une meilleure lisibilité sur les écrans plus petits. */
    /* .map-placement {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100%;
      margin-top: 0;
      } */
      /* Exemple d'ajustement de la taille de police pour les titres */
      .homepage-div h2 {
          font-size: 24px; /* Ajuster la taille de police selon vos besoins */
      }

      /* Exemple d'ajustement de la taille de police pour les paragraphes */
      .homepage-div p {
          font-size: 16px; /* Ajuster la taille de police selon vos besoins */
      }

      /* Ajoutez d'autres styles CSS au besoin pour personnaliser davantage votre mise en page pour les écrans plus petits */
  }
</style>

app/views/houses/_form.html.erb
<%= form_with(model: house) do |form| %>
  <% if house.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
        <% house.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :room_id, style: "display: block" %>
    <%= form.text_field :room_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/houses/_house.html.erb
<div id="<%= dom_id house %>">

  <p>
    <strong>Name:</strong>
    <%= house.name %>
    <%= house.description %>
  </p>

</div>

app/views/houses/edit.html.erb
<h1>Editing house</h1>

<%= render "form", house: @house %>

<br>

<div>
  <%= link_to "Show this house", @house %> |
  <%= link_to "Back to houses", houses_path %>
</div>

app/views/houses/new.html.erb
<h1>New house</h1>

<%= render "form", house: @house %>

<br>

<div>
  <%= link_to "Back to houses", houses_path %>
</div>

app/views/houses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @house %>
<h2>Roooooms:</h2>
<ul>
  <% @house.rooms.each do |room| %>
    <li>
      <h3><%= room.name %></h3>
      <p><%= room.description %></p>
      <p>Price: <%= room.price %></p>
      <p>Status: <%= room.status ? 'Available' : 'Occupied' %></p>
      <%= link_to "Informations supplémentaires", house_room_path(room) %>
    </li>
  <% end %>
</ul>

<div>
  <%= link_to "Back to houses", houses_path %>
</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rooms</h1>

<div id="rooms">
  <% @rooms.each do |room| %>
    <%= render room %>
      <p>
      <%= link_to "Show this room", houses_path %>
      </p>
  <% end %>
</div>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @room %>

<!-- show.html.erb -->

<!-- Boucle pour afficher les photos de la chambre -->
<% @room.photos.each do |photo| %>
  <%= image_tag photo.url %>
<% end %>

<div>
  <%= link_to "Back to rooms", houses_path %>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
      <p>Alcamaya. Tous droits réservés.</p>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar-alcamaya">
    <%= link_to 'Accueil', root_path %>
    <%= link_to 'Appartements', houses_path %>
    <%= link_to 'Beaux et services', beaux_et_services_path %>
    <%= link_to 'Contact', contact_path %>
</nav>

app/views/static_pages/ach1.html.erb
<div class="banner_two">
<div class="container-title">
<h1>Chambre 1</h1>
<p>"La plus calme"</p>
</div>
</div>

<div class="carousel-page">
  <div id="carouselExampleIndicators" class="carousel slide my-carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://zupimages.net/up/24/35/egy0.jpg" class="d-block w-100" alt="ch1p1">
      </div>
      <div class="carousel-item">
        <img src="https://zupimages.net/up/24/35/uaz9.jpg" class="d-block w-100" alt="ch1p2">
      </div>
      <div class="carousel-item">
        <img src="https://zupimages.net/up/24/35/o6ao.jpg" class="d-block w-100" alt="ch1p3">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <div>
  <p>La chambre 1 mesure <strong>13m²</strong> et dispose :<p>
  <ul>
  <p><i class="fa-solid fa-check" style="color: #000000;"></i> Un lit kingsize </p>
  <p><i class="fa-solid fa-check" style="color: #000000;"></i> Un bureau </p>
  <p><i class="fa-solid fa-check" style="color: #000000;"></i> Des rangements adéquats </p>
  <p><i class="fa-solid fa-check" style="color: #000000;"></i> Un grand miroir </p>
  <p><i class="fa-solid fa-check" style="color: #000000;"></i> Table et lampe de chevet </p>
  </ul>

  <p> La chambre est assez loin des parties communes et très calme en sens </p>
  <p><strong>390€ TCC* (voir page Beaux et services)</strong></p>
  <p style="color: green"><strong>Disponible</strong></p>
  <div class="button-coloc-green">
  <button class="button-home style-5" onclick="window.location.href='<%= contact_path %>'">Cliquez ici pour nous contacter</button>
  <button class="button-home style-5" onclick="window.location.href='<%= appart_path %>'">Revenir à la coloc</button>
  </div>
  </div>
</div>

<br>
<br>

<style>
  /* Ajouter des styles CSS pour mobile ici */

  /* Pour changer l'ordre des éléments sur les appareils mobiles */
  @media (max-width: 767px) {
    .carousel-page {
      display: block;
      order: 0; /* Changez l'ordre à 2 pour placer le carrousel en dessous du texte */
    }

    .container-title h1 {
      font-size: 24px;
    }

    .container-title p {
      font-size: 16px;
      margin-left: 10px;
      margin-right: 10px;
    }

      .carousel-page p {
      font-size: 16px;
      margin-left: 10px;
      margin-right: 10px;
    }

    /* Styles supplémentaires pour d'autres éléments mobiles ici */
  }
</style>

app/views/static_pages/ach3.html.erb
<div class="banner_two">
<div class="container-title">
<h1>Chambre 3</h1>
<p>"La plus belle"</p>
</div>
</div>

<div class="carousel-page">
  <div id="carouselExampleIndicators" class="carousel slide my-carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://zupimages.net/up/24/35/ohp3.jpg" class="d-block w-100" alt="ch1p1">
      </div>
      <div class="carousel-item">
        <img src="https://zupimages.net/up/24/35/wvhg.jpg" class="d-block w-100" alt="ch1p2">
      </div>
      <div class="carousel-item">
        <img src="https://zupimages.net/up/24/35/gev8.jpg" class="d-block w-100" alt="ch1p3">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <div>
  <p>La chambre 3 mesure <strong>16m²</strong> et dispose :<p>
  <ul>
  <p><i class="fa-solid fa-check" style="color: #000000;"></i> Un lit kingsize </p>
  <p><i class="fa-solid fa-check" style="color: #000000;"></i> Un bureau </p>
  <p><i class="fa-solid fa-check" style="color: #000000;"></i> Des rangements adéquats </p>
  <p><i class="fa-solid fa-check" style="color: #000000;"></i> Un grand miroir </p>
  <p><i class="fa-solid fa-check" style="color: #000000;"></i> Table et lampe de chevet </p>
  </ul>

  <p> La chambre est très belle et très grande, son côté atypique lui apporte beaucoup de charme </p>
  <p><strong>430€ TCC* (voir page Beaux et services)</strong></p>
  <p style="color: green"><strong>Disponible</strong></p>
  <div class="button-coloc-green">
  <button class="button-home style-5" onclick="window.location.href='<%= contact_path %>'">Cliquez ici pour nous contacter</button>
  <button class="button-home style-5" onclick="window.location.href='<%= appart_path %>'">Revenir à la coloc</button>
  </div>
  </div>
</div>

<br>
<br>

<style>
  /* Ajouter des styles CSS pour mobile ici */

  /* Pour changer l'ordre des éléments sur les appareils mobiles */
  @media (max-width: 767px) {
    .carousel-page {
      display: block;
      order: 0; /* Changez l'ordre à 2 pour placer le carrousel en dessous du texte */
    }

    .container-title h1 {
      font-size: 24px;
    }

    .container-title p {
      font-size: 16px;
      margin-left: 10px;
      margin-right: 10px;
    }

      .carousel-page p {
      font-size: 16px;
      margin-left: 10px;
      margin-right: 10px;
    }

    /* Styles supplémentaires pour d'autres éléments mobiles ici */
  }
</style>

app/views/static_pages/ch1.html.erb
<div class="banner_two">
<div class="container-title">
<h1>Chambre 1</h1>
<p>"La plus cosy"</p>
</div>
</div>

<div class="carousel-page">
  <div id="carouselExampleIndicators" class="carousel slide my-carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://zupimages.net/up/23/36/cxup.jpg" class="d-block w-100" alt="ch1p1">
      </div>
      <div class="carousel-item">
        <img src="https://zupimages.net/up/23/36/mus2.jpg" class="d-block w-100" alt="ch1p2">
      </div>
      <div class="carousel-item">
        <img src="https://zupimages.net/up/23/36/dgzh.jpg" class="d-block w-100" alt="ch1p3">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <div>
  <p>La chambre 1 mesure <strong>13m²</strong> et dispose :<p>
  <ul>
  <p><i class="fa-solid fa-check" style="color: #000000;"></i> Un lit kingsize </p>
  <p><i class="fa-solid fa-check" style="color: #000000;"></i> Un bureau </p>
  <p><i class="fa-solid fa-check" style="color: #000000;"></i> Des rangements adéquats </p>
  <p><i class="fa-solid fa-check" style="color: #000000;"></i> Un grand miroir </p>
  <p><i class="fa-solid fa-check" style="color: #000000;"></i> Table et lampe de chevet </p>
  </ul>

  <p> La chambre est lumineuse avec une belle vue sur l'extérieur, des volets éléctriques et un cadena depuis l'intérieur </p>
  <p><strong>380€ TCC* (voir page Beaux et services)</strong></p>
  <p style="color: red"><strong>Occupée</strong></p>
  <div class="button-coloc-green">
  <button class="button-home style-5" onclick="window.location.href='<%= contact_path %>'">Cliquez ici pour nous contacter</button>
  <button class="button-home style-5" onclick="window.location.href='<%= coloc_path %>'">Revenir à la coloc</button>
  </div>
  </div>
</div>

<br>
<br>

<style>
  /* Ajouter des styles CSS pour mobile ici */

  /* Pour changer l'ordre des éléments sur les appareils mobiles */
  @media (max-width: 767px) {
    .carousel-page {
      display: block;
      order: 0; /* Changez l'ordre à 2 pour placer le carrousel en dessous du texte */
    }

    .container-title h1 {
      font-size: 24px;
    }

    .container-title p {
      font-size: 16px;
      margin-left: 10px;
      margin-right: 10px;
    }

      .carousel-page p {
      font-size: 16px;
      margin-left: 10px;
      margin-right: 10px;
    }

    /* Styles supplémentaires pour d'autres éléments mobiles ici */
  }
</style>